name: FTP Deploy

on:
  push:
    branches:
       - main 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      -  name: Checkout Repository
         uses: actions/checkout@v2
    
      -  name: FTP Transfer
         uses: sebastianpopp/ftp-action@releases/v2
         with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local: "." # Chemin local des fichiers à transférer (par défaut, le répertoire racine du référentiel)
          remote: "/htdocs" # Chemin sur le serveur FTP où les fichiers seront transférés
