name: FTP Deploy

on:
  push:
    branches:
       - main 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      -  name: Checkout Repository
         uses: actions/checkout@v2

      - name: Replace Secrets in Config
        run: |
          sed -i "s/BDD_PASSWORD/${{ secrets.BDD_PASSWORD }}/g" config.php
          sed -i "s/BDD_HOSTNAME/${{ secrets.BDD_HOSTNAME }}/g" config.php
          sed -i "s/BDD_USERNAME/${{ secrets.BDD_USERNAME }}/g" config.php
          
      -  name: FTP Transfer
         uses: sebastianpopp/ftp-action@releases/v2
         with:
          host: ${{ secrets.FTP_HOST }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: "." # Chemin local des fichiers à transférer (par défaut, le répertoire racine du référentiel)
          remoteDir: "/htdocs" # Chemin sur le serveur FTP où les fichiers seront transférés
