name: FTP Deploy

on:
  push:
    branches:
       - main 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      -  name: Checkout Repository
         uses: actions/checkout@v2

      - name: Execute script
        env:
          BDD_PASSWORD: ${{ secrets.BDD_PASSWORD }}
          BDD_HOSTNAME: ${{ secrets.BDD_HOSTNAME }}
          BDD_USERNAME: ${{ secrets.BDD_USERNAME }}
        run: php config.php
          
      -  name: FTP Transfer
         uses: sebastianpopp/ftp-action@releases/v2
         with:
          host: ${{ secrets.FTP_HOST }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: "." # Chemin local des fichiers à transférer (par défaut, le répertoire racine du référentiel)
          remoteDir: "/htdocs" # Chemin sur le serveur FTP où les fichiers seront transférés
